### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 23bca273** [vtcbca/internal-exam-23bca273#3]
![Screenshot (5)](https://github.com/user-attachments/assets/14f4c226-ae0d-4dcc-94e3-1eaee330214d)

**Comment by 23bca274** [comment]
You've to write a variable after " for l in " that will store data which are in " l " variable  then you've to write any statement after for loop that you want to execute . 

Ex : for r in l :
        print( r )

**Comment by 23bca273** [comment]
thank you to suggestion
